### ISSUE TITLE
How to access web3 from layout component?

### ISSUE THREAD

**Issue by vertangelx** [mcarlucci/disperse#1]
If I have a layout component, how can i get the `web3` object so that I can use it?

For example, when a user clicks on a button, it will ask web3 to fetch the current block number.

**Comment by mcarlucci** [comment]
Are you using Ethereum's web3 package? https://github.com/ethereum/web3.js/

**Comment by mcarlucci** [comment]
Closing as this is not an issue with the boilerplate itself.
