### ISSUE TITLE
Npm install doesnt work

### ISSUE THREAD

**Issue by varvarasd** [mcarlucci/disperse#2]
Hi,
I just wanted to give a try to your project but can't pass the Setup with: npm install
Please see below.
I'm using Windows 10 and npm version 5.6

![disperse](https://user-images.githubusercontent.com/21359557/34411738-b4dd3d9e-ebd0-11e7-931c-64605506913d.PNG)

**Comment by mcarlucci** [comment]
This project is primarily for Mac users. However, https://github.com/mcarlucci/disperse/pull/4 should fix your issue.
