### ISSUE TITLE
Npm start doesn't work

### ISSUE THREAD

**Issue by varvarasd** [mcarlucci/disperse#3]
Hi,
I've managed to install npm but now running `npm start` responds as below:

![disperse2](https://user-images.githubusercontent.com/21359557/34413065-e032c880-ebd8-11e7-8402-873efdeaa048.PNG)

**Comment by agrcrobles** [comment]
it just worked for me on mac os

**Comment by lvndry** [comment]
Remove npm install -g ttab in presintall.sh and it will work

**Comment by mcarlucci** [comment]
This project is primarily for Mac users only. However, cross platform additions would be much appreciated if anyone would like to contribute. For now, I am closing this issue as @lvndry added an stop gap solution (https://github.com/mcarlucci/disperse/pull/4) in the meantime. Sorry for the confusion. I will update the README.
