### ISSUE TITLE
npm start => scripts/testrpc.sh: line 6: ttab: command not found

### ISSUE THREAD

**Issue by cichy** [mcarlucci/disperse#5]
Truffle v4.1.3 (core: 4.1.3)
Solidity v0.4.19 (solc-js)

HighSierra 10.13.3

npm start

> disperse@1.0.0 start /Users/.../.../truffle/disperse/disperse
> scripts/testrpc.sh && truffle migrate && node scripts/start.js

scripts/testrpc.sh: line 6: ttab: command not found
Could not connect to your Ethereum client. Please check that your Ethereum client:
    - is running
    - is accepting RPC connections (i.e., "--rpc" option is used in geth)
    - is accessible over the network
    - is properly configured in your Truffle configuration file (truffle.js)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! disperse@1.0.0 start: `scripts/testrpc.sh && truffle migrate && node scripts/start.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the disperse@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/.../.npm/_logs/2018-03-14T15_10_35_843Z-debug.log

**Comment by AmineAfia** [comment]
You need to install ttab: `[sudo] npm install ttab -g`
